title:             Undenailable
email:             undenailable@gmail.com
description:       I do nail art sometimes
author:            Undenailable
baseurl:           ""
url:               "http://undenailable.github.io"

# Social Profiles
twitter_username:  undenailable
instagram_username: undenailable

defaults:
  - scope:
      path: "img/nailart"
    values:
      image: true

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
